[programs.localnet]
messengerapp = "yLcwxfEuFNG5pfNn4VBJ3hhf5UHnMm6mkrpx3Y2vLLD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sohom/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
